### ISSUE TITLE
Compatibility issue with the latest version of sat-search in get_planet

### ISSUE THREAD

**Issue by chlsl** [cmla/tsd#29]
With the most recent version of `sat-search` installed, i.e. `v0.3.0`, `get_planet` fails with the following message:
```
$ python3 get_planet.py --help
Traceback (most recent call last):
  File "/Users/charleshessel/Research/kayrros/tsd/tsd/get_planet.py", line 37, in <module>
    from tsd import utils
  File "/Users/charleshessel/Research/kayrros/tsd/tsd/__init__.py", line 2, in <module>
    from tsd import search_devseed
  File "/Users/charleshessel/Research/kayrros/tsd/tsd/search_devseed.py", line 35, in <module>
    satsearch.config.API_URL = "https://sat-api.developmentseed.org"
AttributeError: module 'satsearch' has no attribute 'config'
```
I replacing `sat-search` with the previous version `v0.2.3` solves the issue.

**Comment by glostis** [comment]
Hey @chlsl,

Indeed, the change you noticed comes from this commit: https://github.com/sat-utils/sat-search/pull/99/commits/80a75c64a8e28c74f3aff1f2c916a29da0e43a40

The "official" fix is to pass a URL to the `Search` object.

**Comment by glostis** [comment]
Apparently @carlodef had already spotted the breaking change and froze the `sat-search` version: https://github.com/cmla/tsd/commit/0967f1dbf4c904e04236bd0bf165da25fdc1109c

**Comment by chlsl** [comment]
Ha, indeed I wasn't on the last version of tsd.
Sorry for that and thanks for your answer @glostis!
