### ISSUE TITLE
Missing images on Sabine Pass Area

### ISSUE THREAD

**Issue by sarahhakim** [cmla/tsd#8]
Example of command used : 
python3 get_sentinel2.py --geom output/sabine_pass.geojson -b B04 B08 -o output

List of images : 
['14/05/2017',
 '24/05/2017',
 '03/06/2017',
 '13/06/2017',
 '23/06/2017',
 '03/07/2017',
 '08/07/2017',
 '13/07/2017',
 '28/07/2017',
 '02/08/2017',
 '12/08/2017',
 '17/08/2017',
 '22/08/2017',
 '01/09/2017',
 '06/09/2017',
 '11/09/2017',
 '26/09/2017',
 '01/10/2017',
 '11/10/2017',
 '21/10/2017',
 '05/11/2017',
 '10/11/2017',
 '15/11/2017',
 '20/11/2017',
 '30/11/2017',
 '05/12/2017',
 '15/12/2017',
 '20/12/2017',
 '25/12/2017',
 '04/01/2018',
 '09/01/2018',
 '14/01/2018',
 '24/01/2018',
 '29/01/2018',
 '03/02/2018',
 '18/02/2018',
 '23/02/2018',
 '28/02/2018',
 '15/03/2018',
 '20/03/2018',
 '25/03/2018',
 '30/03/2018',
 '04/04/2018',
 '14/04/2018',
 '19/04/2018',
 '24/04/2018',
 '04/05/2018',
 '14/05/2018',
 '19/05/2018',
 '24/05/2018',
 '29/05/2018',
 '08/06/2018']

Images from 2017-05-04 found in EO Browser : 
04/05/2017
14/05/2017
24/05/2017
03/06/2017
13/06/2017
23/06/2017
03/07/2017
08/07/2017
13/07/2017
18/07/2017
23/07/2017
28/07/2017
02/08/2017
12/08/2017
17/08/2017
22/08/2017
27/08/2017
01/09/2017
06/09/2017
11/09/2017
21/09/2017
26/09/2017
01/10/2017
06/10/2017
11/10/2017
16/10/2017
21/10/2017
31/10/2017
05/11/2017
10/11/2017
15/11/2017
20/11/2017
30/11/2017
05/12/2017
15/12/2017
20/12/2017
25/12/2017
04/01/2018
09/01/2018
14/01/2018
24/01/2018
29/01/2018
03/02/2018
08/02/2018
18/02/2018
23/02/2018
05/03/2018
10/03/2018
15/03/2018
20/03/2018
25/03/2018
20/03/2018
04/04/2018
09/04/2018
14/04/2018
19/04/2018
24/04/2018
29/04/2018
04/05/2018
09/05/2018
14/05/2018
19/05/2018
24/05/2018
29/05/2018
03/06/2018
08/06/2018

for example, images available in EO browser but not in our list : 03/06/2018, 09/05/2018

**Comment by carlodef** [comment]
The missing images are missing from [developmentseed API](https://api.developmentseed.org/satellites/) index, which is used by TSD as the default catalogue as it doesn't require authentication.

If you use the [scihub API](https://scihub.copernicus.eu/dhus/#/home) by adding the optional parameter `--api scihub` to your cmdline you'll get more images. This requires authentication with your Copernicus/Scihub credentials stored in the `COPERNICUS_LOGIN` and `COPERNICUS_PASSWORD` environment variables.

    python3 get_sentinel2.py --geom output/sabine_pass.geojson -b B04 -s 2017-5-3 -o output

The EO browser images that are still missing from this TSD call should be only incomplete images (ie images that don't cover the entire geojson polygon) as TSD searches only for images that *contain* the polygon while EO browser searches for images that *intersect* the polygon.
